//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LuccaDevisesMultiUsage {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LuccaDevisesMultiUsage.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Il n&apos;est pas possible de convertir la devise d&apos;origine en la devise finale avec les données actuelles du fichier..
        /// </summary>
        internal static string InconvertibleCurrency {
            get {
                return ResourceManager.GetString("InconvertibleCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La première ligne doit contenir :
        ///    La devise initiale D1 dans laquelle le montant est affiché, sous la forme d&apos;un code de 3 caractères
        ///    Le montant M dans cette devise initiale, sous la forme d&apos;un nombre entier positif &gt; 0
        ///    La devise cible D2 vers laquelle il veut convertir le montant, sous la forme d&apos;un code de 3 caractères
        ///    Les informations vous sont transmises au format D1;M;D2&quot;.
        /// </summary>
        internal static string Line1Usage {
            get {
                return ResourceManager.GetString("Line1Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le deuxième ligne doit indiquer le nombre de ligne de taux de change transmis..
        /// </summary>
        internal static string Line2Usage {
            get {
                return ResourceManager.GetString("Line2Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La ligne {0} ne décrit pas correctement un taux de change représenté ainsi :
        ///    La devise de départ DD sous la forme d&apos;un code de 3 caractères
        ///    La devise d&apos;arrivée DA sous la forme d&apos;un code de 3 caractères
        ///    Le taux de change T sous la forme d&apos;un nombre à 4 décimales (avec un &quot;&quot;.&quot;&quot; comme séparateur décimal)
        ///    Les informations vous sont transmises au format DD; DA; T.
        /// </summary>
        internal static string Line3Usage {
            get {
                return ResourceManager.GetString("Line3Usage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Merci d&apos;indiquer le chemin du fichier de devise à utiliser.
        /// </summary>
        internal static string NoFileParameter {
            get {
                return ResourceManager.GetString("NoFileParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le fichier ne contient pas les données nécessaire pour effectuer une conversion..
        /// </summary>
        internal static string NotEnoughRows {
            get {
                return ResourceManager.GetString("NotEnoughRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Le nombre de ligne de taux de change du fichier : {0} et le nombre de supposé inscrit dans la deuxième ligne : {1} ne sont pas cohérents..
        /// </summary>
        internal static string UnexpectedNumberOfRows {
            get {
                return ResourceManager.GetString("UnexpectedNumberOfRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Les arguments ne forment pas un chemin de fichier valide, merci de vérifier le chemin passé en paramètre..
        /// </summary>
        internal static string UnvalidFileParameter {
            get {
                return ResourceManager.GetString("UnvalidFileParameter", resourceCulture);
            }
        }
    }
}
